name: graph_network
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.7=py38h9128911_0
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2025.9.9=haa95532_0
  - certifi=2024.8.30=py38haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.7=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - libffi=3.4.4=hd77b12b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - networkx=3.1=py38haa95532_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openssl=3.0.17=h35632f6_0
  - packaging=24.1=py38haa95532_0
  - pandas=2.0.3=py38h4ed8f06_0
  - pip=24.2=py38haa95532_0
  - platformdirs=3.10.0=py38haa95532_0
  - pooch=1.7.0=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0post0=py38haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2024.1=py38haa95532_0
  - requests=2.32.3=py38haa95532_0
  - scipy=1.10.1=py38hdcfc7df_1
  - setuptools=75.1.0=py38haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.50.2=hda9a48d_1
  - tbb=2021.8.0=h59b6b97_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.2.3=py38haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
prefix: D:\Miniforge\envs\graph_network
